version: '3'
services:
  chatbot:
    image: gamtin21/chatbot:1.0
    environment:
      - TELEGRAM_ACCESS_TOKEN=6296839838:AAFAo3mYsnggz-ERkCTZUDNd_MrWZcgSeDw
      - REDIS_HOST=redis
      - REDIS_PASSWORD=comp7940passwordlab8
      - REDIS_PORT=6379
      - YOUTUBE_API_KEY=AIzaSyCw70b8J5ytEi0RUXi0Byxipt2peQbUwFI
    entrypoint: python chatbot.py
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]